name: notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.11.1
  - pytest=5.4.3
  - black=19.10b0
  - nb_black=1.0.7
  - pylint=2.5.3
  - jupyterlab=2.1.5
  - jupyter_conda=3.3.1
  - black=19.10b0
  - pip=20.1.1
  - matplotlib=3.3.1
  - pylint=2.5.3
  - pytest=5.4.3
  - python=3.8
  - jupyter
  - xgboost=1.2.0
  - lightgbm=3.1.0
  - catboost==0.24.4
